[package]
name = "parameter-on-off-nih-plug"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
parameter = { path = "../parameter" }
parameter-on-off = { path = "../parameter-on-off" }
parameter-nih-plug = { path = "../parameter-nih-plug" }
num-traits = "0.2.19"
nice-plug = { git = "https://codeberg.org/valsteen/nice-plug.git", rev = "211a6f32130dede2c493ddc8d88ea09f5be8e314", version = "0.2.0", default-features = false }

[lints]
workspace = true

[[test]]
name = "generated_group"
path = "tests/integration/generated_group.rs"
