[package]
name = "sync"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219" }
atomic = "0.6.1"
num-traits = "0.2.19"
bytemuck = "1.23.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
parking_lot = { version = "0.12.4" }

[lints]
workspace = true
