//! nice-plug adapters for parameter metadata generated by `#[parameter_group]`.
//!
//! `#[nice_plugin_parameter_group(config = ..., group = "...")]` uses the `config`
//! path as the public descriptor contract for generated mirror methods. For a
//! config path like `some_crate::module::ExampleConfig`, the macro looks for
//! field descriptor marker types next to that path, such as
//! `some_crate::module::ExampleGainField`. If the config type is re-exported,
//! re-export the generated descriptor markers at the same public path.

use std::{collections::BTreeMap, sync::Arc, time::Duration};

use nice_plug::{
    params::{FloatParam, IntParam, Param},
    prelude::{FloatRange, IntRange, ParamPtr, ParamSetter, RemoteControlsPage},
};
use num_traits::ToPrimitive;
use parameter::{Parameter, ParameterField};
pub use parameter_nice_plug_macros::nice_plugin_parameter_group;

pub trait GeneratedNicePlugParams {}

/// Mirrors only changed config fields into nice-plug host parameters.
///
/// The returned complete typed config is the mirror the caller can retain as
/// its next draft.
pub trait MirrorChangedConfig {
    /// The complete typed config mirrored by this host parameter group.
    type Config: Clone;

    /// Mirrors fields that differ between `before` and `after`, then returns the
    /// complete typed mirror for the caller's next draft.
    #[must_use]
    fn mirror_changed_config(
        &self,
        before: &Self::Config,
        after: &Self::Config,
        param_setter: &nice_plug::prelude::ParamSetter<'_>,
    ) -> Self::Config;
}

pub trait NicePlugFieldAdapter<Config, Value> {
    type HostParam;

    fn to_host_param<OnChange>(
        field: &ParameterField<Config, Value>,
        config: &Config,
        on_change: &OnChange,
    ) -> Self::HostParam
    where
        OnChange: Fn() + Clone + Send + Sync + 'static;

    fn set_config_from_host_param(parameter: &Parameter<Config, Value>, config: &mut Config, param: &Self::HostParam);

    fn add_param_map(param: &Self::HostParam, params: &mut Vec<(String, ParamPtr, String)>);

    fn serialize_fields(param: &Self::HostParam, serialized: &mut BTreeMap<String, String>);

    fn deserialize_fields(param: &Self::HostParam, serialized: &BTreeMap<String, String>);

    fn add_remote_control(param: &Self::HostParam, page: &mut impl RemoteControlsPage);
}

pub trait MirrorHostParam<Config, Value> {
    fn mirror_host_param(
        &self,
        config: &mut Config,
        parameter: &Parameter<Config, Value>,
        value: Value,
        param_setter: &ParamSetter<'_>,
    );
}

pub trait ToNicePlugParam<ValueType> {
    type Param: Param;

    fn to_param<OnChange>(&self, value: ValueType, on_change: &OnChange) -> Self::Param
    where
        OnChange: Fn() + Clone + Send + Sync + 'static;
}

pub fn to_plugin_float_param<Config, ValueType, OnChange>(
    parameter: &Parameter<Config, ValueType>,
    config: &Config,
    on_change: &OnChange,
) -> FloatParam
where
    Parameter<Config, ValueType>: ToNicePlugParam<ValueType, Param = FloatParam>,
    OnChange: Fn() + Clone + Send + Sync + 'static,
{
    let value = (parameter.get)(config);

    parameter.to_param(value, on_change)
}

pub fn to_plugin_int_param<Config, ValueType, OnChange>(
    parameter: &Parameter<Config, ValueType>,
    config: &Config,
    on_change: &OnChange,
) -> IntParam
where
    Parameter<Config, ValueType>: ToNicePlugParam<ValueType, Param = IntParam>,
    OnChange: Fn() + Clone + Send + Sync + 'static,
{
    let value = (parameter.get)(config);

    parameter.to_param(value, on_change)
}

pub fn to_plugin_u16_logarithmic_param<Config, OnChange>(
    parameter: &Parameter<Config, u16>,
    config: &Config,
    on_change: &OnChange,
) -> FloatParam
where
    OnChange: Fn() + Clone + Send + Sync + 'static,
{
    u16_range_to_logarithmic_param(parameter, (parameter.get)(config), on_change)
}

pub trait SetConfigFromFloatParam<Config>: Sized {
    fn set_config_from_float_param(parameter: &Parameter<Config, Self>, config: &mut Config, param: &FloatParam);
}

pub fn set_config_from_float_param<Config, ValueType>(
    parameter: &Parameter<Config, ValueType>,
    config: &mut Config,
    param: &FloatParam,
) where
    ValueType: SetConfigFromFloatParam<Config>,
{
    ValueType::set_config_from_float_param(parameter, config, param);
}

pub trait SetConfigFromIntParam<Config>: Sized {
    fn set_config_from_int_param(parameter: &Parameter<Config, Self>, config: &mut Config, param: &IntParam);
}

pub fn set_config_from_int_param<Config, ValueType>(
    parameter: &Parameter<Config, ValueType>,
    config: &mut Config,
    param: &IntParam,
) where
    ValueType: SetConfigFromIntParam<Config>,
{
    ValueType::set_config_from_int_param(parameter, config, param);
}

macro_rules! impl_to_param_for_float {
    ($float_type:ty) => {
        impl<Config> ToNicePlugParam<$float_type> for Parameter<Config, $float_type> {
            type Param = FloatParam;

            fn to_param<OnChange>(&self, value: $float_type, on_change: &OnChange) -> Self::Param
            where
                OnChange: Fn() + Clone + Send + Sync + 'static,
            {
                let range = if self.spec.logarithmic {
                    FloatRange::Skewed {
                        min: metadata_f64_to_f32(*self.spec.range.start()),
                        max: metadata_f64_to_f32(*self.spec.range.end()),
                        factor: 0.3,
                    }
                } else {
                    FloatRange::Linear {
                        min: metadata_f64_to_f32(*self.spec.range.start()),
                        max: metadata_f64_to_f32(*self.spec.range.end()),
                    }
                };

                let on_change = on_change.clone();
                let mut param = FloatParam::new(self.spec.label, parameter_value_to_f32(&value), range)
                    .with_callback(Arc::new(move |_| on_change()));
                if let Some(unit) = self.spec.unit {
                    param = param.with_unit(unit);
                }
                if self.spec.step > 0.0 {
                    param = param.with_step_size(metadata_f64_to_f32(self.spec.step));
                }

                param.with_value_to_string(Arc::new(|value| format!("{value:.2}")))
            }
        }
    };
}

macro_rules! impl_to_param_for_integer {
    ($int_type:ty) => {
        impl<Config> ToNicePlugParam<$int_type> for Parameter<Config, $int_type> {
            type Param = IntParam;

            fn to_param<OnChange>(&self, value: $int_type, on_change: &OnChange) -> Self::Param
            where
                OnChange: Fn() + Clone + Send + Sync + 'static,
            {
                let on_change = on_change.clone();
                let mut param = IntParam::new(
                    self.spec.label,
                    parameter_value_to_i32(&value),
                    IntRange::Linear {
                        min: metadata_f64_to_i32(*self.spec.range.start()),
                        max: metadata_f64_to_i32(*self.spec.range.end()),
                    },
                )
                .with_callback(Arc::new(move |_| on_change()));
                if let Some(unit) = self.spec.unit {
                    param = param.with_unit(unit);
                }

                param
            }
        }
    };
}

impl_to_param_for_float!(f32);
impl_to_param_for_float!(f64);
impl_to_param_for_integer!(u16);
impl_to_param_for_integer!(u8);

impl<Config> ToNicePlugParam<Duration> for Parameter<Config, Duration> {
    type Param = FloatParam;

    fn to_param<OnChange>(&self, value: Duration, on_change: &OnChange) -> Self::Param
    where
        OnChange: Fn() + Clone + Send + Sync + 'static,
    {
        float_param_from_metadata(self, value.as_secs_f32(), on_change)
    }
}

impl<Config> MirrorHostParam<Config, f32> for FloatParam {
    fn mirror_host_param(
        &self,
        config: &mut Config,
        parameter: &Parameter<Config, f32>,
        value: f32,
        param_setter: &ParamSetter<'_>,
    ) {
        (parameter.set)(config, value);
        set_float_host_param(self, &value, param_setter);
    }
}

impl<Config> MirrorHostParam<Config, f64> for FloatParam {
    fn mirror_host_param(
        &self,
        config: &mut Config,
        parameter: &Parameter<Config, f64>,
        value: f64,
        param_setter: &ParamSetter<'_>,
    ) {
        (parameter.set)(config, value);
        set_float_host_param(self, &value, param_setter);
    }
}

impl<Config> MirrorHostParam<Config, u16> for FloatParam {
    fn mirror_host_param(
        &self,
        config: &mut Config,
        parameter: &Parameter<Config, u16>,
        value: u16,
        param_setter: &ParamSetter<'_>,
    ) {
        (parameter.set)(config, value);
        set_float_host_param(self, &value, param_setter);
    }
}

impl<Config> MirrorHostParam<Config, Duration> for FloatParam {
    fn mirror_host_param(
        &self,
        config: &mut Config,
        parameter: &Parameter<Config, Duration>,
        value: Duration,
        param_setter: &ParamSetter<'_>,
    ) {
        (parameter.set)(config, value);
        set_duration_host_param(self, value, param_setter);
    }
}

impl<Config> MirrorHostParam<Config, u8> for IntParam {
    fn mirror_host_param(
        &self,
        config: &mut Config,
        parameter: &Parameter<Config, u8>,
        value: u8,
        param_setter: &ParamSetter<'_>,
    ) {
        (parameter.set)(config, value);
        set_int_host_param(self, &value, param_setter);
    }
}

impl<Config> MirrorHostParam<Config, u16> for IntParam {
    fn mirror_host_param(
        &self,
        config: &mut Config,
        parameter: &Parameter<Config, u16>,
        value: u16,
        param_setter: &ParamSetter<'_>,
    ) {
        (parameter.set)(config, value);
        set_int_host_param(self, &value, param_setter);
    }
}

impl<Config> SetConfigFromFloatParam<Config> for f32 {
    fn set_config_from_float_param(parameter: &Parameter<Config, Self>, config: &mut Config, param: &FloatParam) {
        (parameter.set)(config, param.unmodulated_plain_value());
    }
}

impl<Config> SetConfigFromFloatParam<Config> for f64 {
    fn set_config_from_float_param(parameter: &Parameter<Config, Self>, config: &mut Config, param: &FloatParam) {
        (parameter.set)(config, f64::from(param.unmodulated_plain_value()));
    }
}

impl<Config> SetConfigFromFloatParam<Config> for u16 {
    fn set_config_from_float_param(parameter: &Parameter<Config, Self>, config: &mut Config, param: &FloatParam) {
        (parameter.set)(config, float_param_value_to_u16(param));
    }
}

impl<Config> SetConfigFromFloatParam<Config> for Duration {
    fn set_config_from_float_param(parameter: &Parameter<Config, Self>, config: &mut Config, param: &FloatParam) {
        (parameter.set)(config, Duration::from_secs_f32(param.unmodulated_plain_value()));
    }
}

impl<Config> SetConfigFromIntParam<Config> for u16 {
    fn set_config_from_int_param(parameter: &Parameter<Config, Self>, config: &mut Config, param: &IntParam) {
        (parameter.set)(config, int_param_value_to_u16(param));
    }
}

impl<Config> SetConfigFromIntParam<Config> for u8 {
    fn set_config_from_int_param(parameter: &Parameter<Config, Self>, config: &mut Config, param: &IntParam) {
        (parameter.set)(config, int_param_value_to_u8(param));
    }
}

fn u16_range_to_logarithmic_param<Config, OnChange>(
    parameter: &Parameter<Config, u16>,
    value: u16,
    on_change: &OnChange,
) -> FloatParam
where
    OnChange: Fn() + Clone + Send + Sync + 'static,
{
    let on_change = on_change.clone();
    let mut param = FloatParam::new(
        parameter.spec.label,
        f32::from(value),
        FloatRange::Skewed {
            min: metadata_f64_to_f32(*parameter.spec.range.start()),
            max: metadata_f64_to_f32(*parameter.spec.range.end()),
            factor: 0.3,
        },
    )
    .with_callback(Arc::new(move |_| on_change()));
    if let Some(unit) = parameter.spec.unit {
        param = param.with_unit(unit);
    }
    param.with_step_size(metadata_f64_to_f32(parameter.spec.step.max(1.0)))
}

fn float_param_from_metadata<Config, ValueType, OnChange>(
    parameter: &Parameter<Config, ValueType>,
    value: f32,
    on_change: &OnChange,
) -> FloatParam
where
    OnChange: Fn() + Clone + Send + Sync + 'static,
{
    let range = if parameter.spec.logarithmic {
        FloatRange::Skewed {
            min: metadata_f64_to_f32(*parameter.spec.range.start()),
            max: metadata_f64_to_f32(*parameter.spec.range.end()),
            factor: 0.3,
        }
    } else {
        FloatRange::Linear {
            min: metadata_f64_to_f32(*parameter.spec.range.start()),
            max: metadata_f64_to_f32(*parameter.spec.range.end()),
        }
    };

    let on_change = on_change.clone();
    let mut param = FloatParam::new(parameter.spec.label, value, range).with_callback(Arc::new(move |_| on_change()));
    if let Some(unit) = parameter.spec.unit {
        param = param.with_unit(unit);
    }
    if parameter.spec.step > 0.0 {
        param = param.with_step_size(metadata_f64_to_f32(parameter.spec.step));
    }

    param.with_value_to_string(Arc::new(|value| format!("{value:.2}")))
}

fn metadata_f64_to_f32(value: f64) -> f32 {
    value.to_f32().expect("parameter metadata should fit in nice-plug f32 values")
}

fn metadata_f64_to_i32(value: f64) -> i32 {
    value.to_i32().expect("parameter metadata should fit in nice-plug i32 values")
}

fn parameter_value_to_f32(value: &impl ToPrimitive) -> f32 {
    value.to_f32().expect("parameter value should fit in nice-plug f32 values")
}

fn parameter_value_to_i32(value: &impl ToPrimitive) -> i32 {
    value.to_i32().expect("parameter value should fit in nice-plug i32 values")
}

fn set_float_host_param(value_param: &FloatParam, value: &impl ToPrimitive, param_setter: &ParamSetter<'_>) {
    param_setter.begin_set_parameter(value_param);
    param_setter.set_parameter(value_param, parameter_value_to_f32(value));
    param_setter.end_set_parameter(value_param);
}

fn set_duration_host_param(value_param: &FloatParam, value: Duration, param_setter: &ParamSetter<'_>) {
    param_setter.begin_set_parameter(value_param);
    param_setter.set_parameter(value_param, value.as_secs_f32());
    param_setter.end_set_parameter(value_param);
}

fn set_int_host_param(value_param: &IntParam, value: &impl ToPrimitive, param_setter: &ParamSetter<'_>) {
    param_setter.begin_set_parameter(value_param);
    param_setter.set_parameter(value_param, parameter_value_to_i32(value));
    param_setter.end_set_parameter(value_param);
}

fn float_param_value_to_u16(param: &FloatParam) -> u16 {
    param.unmodulated_plain_value().to_u16().expect("FloatParam value should fit in u16 config field")
}

fn int_param_value_to_u16(param: &IntParam) -> u16 {
    param.unmodulated_plain_value().to_u16().expect("IntParam value should fit in u16 config field")
}

fn int_param_value_to_u8(param: &IntParam) -> u8 {
    param.unmodulated_plain_value().to_u8().expect("IntParam value should fit in u8 config field")
}
