[package]
name = "errors"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
backtrace = "0.3.69"
strip-ansi-escapes = "0.2.0"
better-panic = "0.3.0"
tracing-error = "0.2.0"
sync = { path = "../sync" }
build = { path = "../build" }
env_logger = "0.11.1"
log = "0.4.20"

[target.'cfg(target_arch = "wasm32")'.dependencies]
minitrace = { version = "0.6.3" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
minitrace = { version = "0.6.3", features = ["enable"] }
human-panic = "1.0.3"

[build-dependencies]
serde_json = { version = "1.0.108", features = [] }

[lints]
workspace = true
