[package]
name = "midi-bpm-detector-plugin"
version.workspace = true
edition = "2024"
authors = ["Vincent Alsteen <vincent.alsteen@gmail.com>"]
license = "MIT"
homepage = "https://github.com/valsteen/midi_bpm_detection"
description = "Midi plugin that will estimate the BPM of the midi input"

[features]
default = ["clap", "standalone"]
clap = []
standalone = ["nice-plug/standalone"]
vst3 = ["nice-plug/vst3"]

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "midi-bpm-detector-plugin"
path = "src/main.rs"
required-features = ["standalone"]

[dependencies]
errors = { path = "../../support/errors" }
gui = { path = "../../bpm/gui" }
bpm_detection_config = { path = "../../bpm/domain/bpm_detection_config" }
bpm_detection_core = { path = "../../bpm/domain/bpm_detection_core" }
parameter = { path = "../../foundation/parameter" }
parameter-on-off = { path = "../../foundation/parameter-on-off" }
parameter-on-off-nih-plug = { path = "../../foundation/parameter-on-off-nih-plug", default-features = false }
parameter-nih-plug = { path = "../../foundation/parameter-nih-plug", default-features = false }
sync = { path = "../../support/sync" }

chrono = "0.4.45"
cpal = "0.18.1"
crossbeam = "0.8.4"
midir = "0.11.0"
num-traits = "0.2.19"
ringbuf = "0.5.0"
serde = { version = "1.0.228", features = ["derive"] }
mimalloc = "0.1.52"
wmidi = "4.0.11"

toml = "1.1.2"
nice-plug = { git = "https://codeberg.org/valsteen/nice-plug.git", rev = "211a6f32130dede2c493ddc8d88ea09f5be8e314", version = "0.2.0", default-features = false, features = ["assert_process_allocs"] }
nice-plug-egui = { git = "https://codeberg.org/valsteen/nice-plug.git", rev = "211a6f32130dede2c493ddc8d88ea09f5be8e314", version = "0.3.0" }

[lints]
workspace = true
