[package]
name = "parameter-on-off-nice-plug"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
parameter = { path = "../parameter" }
parameter-on-off = { path = "../parameter-on-off" }
parameter-nice-plug = { path = "../parameter-nice-plug" }
num-traits = "0.2.19"
nice-plug = { git = "https://codeberg.org/valsteen/nice-plug.git", rev = "d40fec783b978b73dadb3a8ce78e0eea6fde2ab2", version = "0.2.0", default-features = false }

[lints]
workspace = true

[[test]]
name = "generated_group"
path = "tests/integration/generated_group.rs"
