send_tempo = true

[GUI]
interpolation_curve = 0.800000011920929

[GUI.interpolation_duration]
secs = 0
nanos = 730000000

[static_bpm_detection_parameters]
bpm_center = 100.0
bpm_range = 70
sample_rate = 600

[static_bpm_detection_parameters.normal_distribution]
std_dev = 24.0
factor = 47.0
imprecision = 2000.0
resolution = 0.25

[dynamic_bpm_detection_parameters]
beats_lookback = 8

[dynamic_bpm_detection_parameters.velocity_current_note_weight]
enabled = false
value = 0.699999988079071

[dynamic_bpm_detection_parameters.velocity_note_from_weight]
enabled = false
value = 0.6499999761581421

[dynamic_bpm_detection_parameters.age_weight]
enabled = true
value = 1.05

[dynamic_bpm_detection_parameters.octave_distance_weight]
enabled = false
value = 0.6499999761581421

[dynamic_bpm_detection_parameters.pitch_distance_weight]
enabled = false
value = 0.8500000238418579

[dynamic_bpm_detection_parameters.multiplier_weight]
enabled = true
value = 1.8

[dynamic_bpm_detection_parameters.subdivision_weight]
enabled = true
value = 0.5

[dynamic_bpm_detection_parameters.in_beat_range_weight]
enabled = false
value = 0

[dynamic_bpm_detection_parameters.normal_distribution_weight]
enabled = true
value = 1.0

[dynamic_bpm_detection_parameters.high_tempo_bias]
enabled = true
value = 0.95
