[package]
name = "parameter"
version = "0.1.0"
edition = "2024"

[dependencies]
getset = "0.1.2"
serde = { version = "1.0.195", features = ["derive"] }
num-traits = "0.2.19"

[lints]
workspace = true
