# This provides metadata for NIH-plug's `cargo xtask bundle <foo>` midi-bpm-detector-plugin
# bundler. This file's syntax is as follows:
#
# [package_name]
# name = "Human Readable Plugin Name"  # defaults to <package_name>

[midi-bpm-detector-plugin]
name = "Midi BPM Detector"
