[package]
name = "midi-bpm-detector-plugin"
version = "0.1.0"
edition = "2021"
authors = ["Vincent Alsteen <vincent.alsteen@gmail.com>"]
license = "Other licenses can be set in Cargo.toml, but using the project needs to be GPLv3 compliant to be able to use the VST3 exporter. Check Cargo.toml for more information."
homepage = "https://youtu.be/dQw4w9WgXcQ"
description = "Midi plugin that will estimate the BPM of the midi input"


[lib]
crate-type = ["cdylib", "lib"]


[dependencies]
errors = { path = "../errors" }
gui = { path = "../gui" }
midi = { path = "../midi" }
parameter = { path = "../parameter" }
sync = { path = "../sync" }

nih_plug = { path = "../../../nih-plug", features = ["assert_process_allocs", "standalone"] }
nih_plug_egui = { path = "../../../nih-plug/nih_plug_egui" }

atomic_float = "0.1"
atomic_refcell = "0.1.13"
chrono = "0.4.34"
config = "0.14.0"
cpal = "0.15.2"
crossbeam = "0.8.4"
midir = "0.9.1"
num-traits = "0.2.18"
ringbuf = "0.3.3"
serde = { version = "1.0.196", features = ["derive"] }
toml = "0.8.9"

[lints]
workspace = true
